# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CreateWaveDialog.ui'
#
# Created: Thu Feb 17 21:40:08 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreateWaveDialog(object):
    def setupUi(self, CreateWaveDialog):
        CreateWaveDialog.setObjectName(_fromUtf8("CreateWaveDialog"))
        CreateWaveDialog.resize(418, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateWaveDialog.sizePolicy().hasHeightForWidth())
        CreateWaveDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(CreateWaveDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(CreateWaveDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.waveName = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveName.sizePolicy().hasHeightForWidth())
        self.waveName.setSizePolicy(sizePolicy)
        self.waveName.setObjectName(_fromUtf8("waveName"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.waveName)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dataType = QtGui.QComboBox(self.groupBox)
        self.dataType.setObjectName(_fromUtf8("dataType"))
        self.dataType.addItem(_fromUtf8(""))
        self.dataType.addItem(_fromUtf8(""))
        self.dataType.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dataType)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.createWaveButton = QtGui.QPushButton(CreateWaveDialog)
        self.createWaveButton.setObjectName(_fromUtf8("createWaveButton"))
        self.gridLayout.addWidget(self.createWaveButton, 3, 0, 1, 1)
        self.closeWindowButton = QtGui.QPushButton(CreateWaveDialog)
        self.closeWindowButton.setObjectName(_fromUtf8("closeWindowButton"))
        self.gridLayout.addWidget(self.closeWindowButton, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(CreateWaveDialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.waveDataSelectionList = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveDataSelectionList.sizePolicy().hasHeightForWidth())
        self.waveDataSelectionList.setSizePolicy(sizePolicy)
        self.waveDataSelectionList.setMinimumSize(QtCore.QSize(120, 0))
        self.waveDataSelectionList.setObjectName(_fromUtf8("waveDataSelectionList"))
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        self.horizontalLayout.addWidget(self.waveDataSelectionList)
        self.waveDataStack = QtGui.QStackedWidget(self.groupBox_2)
        self.waveDataStack.setFrameShape(QtGui.QFrame.StyledPanel)
        self.waveDataStack.setFrameShadow(QtGui.QFrame.Plain)
        self.waveDataStack.setLineWidth(1)
        self.waveDataStack.setObjectName(_fromUtf8("waveDataStack"))
        self.basicTab = QtGui.QWidget()
        self.basicTab.setObjectName(_fromUtf8("basicTab"))
        self.formLayout = QtGui.QFormLayout(self.basicTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.basicTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.basicWaveType = QtGui.QComboBox(self.basicTab)
        self.basicWaveType.setMinimumSize(QtCore.QSize(150, 0))
        self.basicWaveType.setObjectName(_fromUtf8("basicWaveType"))
        self.basicWaveType.addItem(_fromUtf8(""))
        self.basicWaveType.addItem(_fromUtf8(""))
        self.basicWaveType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.basicWaveType)
        self.label_9 = QtGui.QLabel(self.basicTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.basicWaveLength = QtGui.QSpinBox(self.basicTab)
        self.basicWaveLength.setMaximum(999999)
        self.basicWaveLength.setObjectName(_fromUtf8("basicWaveLength"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.basicWaveLength)
        self.waveDataStack.addWidget(self.basicTab)
        self.copyTab = QtGui.QWidget()
        self.copyTab.setObjectName(_fromUtf8("copyTab"))
        self.formLayout_3 = QtGui.QFormLayout(self.copyTab)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.copyTab)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.copyWaveOriginalWave = QtGui.QComboBox(self.copyTab)
        self.copyWaveOriginalWave.setObjectName(_fromUtf8("copyWaveOriginalWave"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.copyWaveOriginalWave)
        self.label_6 = QtGui.QLabel(self.copyTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.copyWaveStartingIndex = QtGui.QSpinBox(self.copyTab)
        self.copyWaveStartingIndex.setObjectName(_fromUtf8("copyWaveStartingIndex"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.copyWaveStartingIndex)
        self.label_8 = QtGui.QLabel(self.copyTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.copyWaveEndingIndex = QtGui.QSpinBox(self.copyTab)
        self.copyWaveEndingIndex.setObjectName(_fromUtf8("copyWaveEndingIndex"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.copyWaveEndingIndex)
        self.waveDataStack.addWidget(self.copyTab)
        self.functionTab = QtGui.QWidget()
        self.functionTab.setObjectName(_fromUtf8("functionTab"))
        self.formLayout_4 = QtGui.QFormLayout(self.functionTab)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_7 = QtGui.QLabel(self.functionTab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.functionWaveLength = QtGui.QSpinBox(self.functionTab)
        self.functionWaveLength.setMaximum(9999999)
        self.functionWaveLength.setObjectName(_fromUtf8("functionWaveLength"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.functionWaveLength)
        self.label_5 = QtGui.QLabel(self.functionTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.functionEquation = QtGui.QLineEdit(self.functionTab)
        self.functionEquation.setObjectName(_fromUtf8("functionEquation"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.functionEquation)
        self.functionInsertWaveButton = QtGui.QPushButton(self.functionTab)
        self.functionInsertWaveButton.setObjectName(_fromUtf8("functionInsertWaveButton"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.functionInsertWaveButton)
        self.functionInsertWave = QtGui.QComboBox(self.functionTab)
        self.functionInsertWave.setObjectName(_fromUtf8("functionInsertWave"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.functionInsertWave)
        self.waveDataStack.addWidget(self.functionTab)
        self.horizontalLayout.addWidget(self.waveDataStack)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)

        self.retranslateUi(CreateWaveDialog)
        self.waveDataSelectionList.setCurrentRow(-1)
        self.waveDataStack.setCurrentIndex(2)
        QtCore.QObject.connect(self.waveDataSelectionList, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.waveDataStack.setCurrentIndex)
        CreateWaveDialog.setTabOrder(self.waveName, self.dataType)
        CreateWaveDialog.setTabOrder(self.dataType, self.waveDataSelectionList)
        CreateWaveDialog.setTabOrder(self.waveDataSelectionList, self.basicWaveType)
        CreateWaveDialog.setTabOrder(self.basicWaveType, self.basicWaveLength)
        CreateWaveDialog.setTabOrder(self.basicWaveLength, self.copyWaveOriginalWave)
        CreateWaveDialog.setTabOrder(self.copyWaveOriginalWave, self.copyWaveStartingIndex)
        CreateWaveDialog.setTabOrder(self.copyWaveStartingIndex, self.copyWaveEndingIndex)
        CreateWaveDialog.setTabOrder(self.copyWaveEndingIndex, self.functionWaveLength)
        CreateWaveDialog.setTabOrder(self.functionWaveLength, self.functionEquation)
        CreateWaveDialog.setTabOrder(self.functionEquation, self.functionInsertWaveButton)
        CreateWaveDialog.setTabOrder(self.functionInsertWaveButton, self.functionInsertWave)
        CreateWaveDialog.setTabOrder(self.functionInsertWave, self.createWaveButton)
        CreateWaveDialog.setTabOrder(self.createWaveButton, self.closeWindowButton)

    def retranslateUi(self, CreateWaveDialog):
        CreateWaveDialog.setWindowTitle(QtGui.QApplication.translate("CreateWaveDialog", "Create Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CreateWaveDialog", "Wave Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateWaveDialog", "Wave Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CreateWaveDialog", "Wave Data Type", None, QtGui.QApplication.UnicodeUTF8))
        self.dataType.setItemText(0, QtGui.QApplication.translate("CreateWaveDialog", "Integer", None, QtGui.QApplication.UnicodeUTF8))
        self.dataType.setItemText(1, QtGui.QApplication.translate("CreateWaveDialog", "Decimal", None, QtGui.QApplication.UnicodeUTF8))
        self.dataType.setItemText(2, QtGui.QApplication.translate("CreateWaveDialog", "String", None, QtGui.QApplication.UnicodeUTF8))
        self.createWaveButton.setText(QtGui.QApplication.translate("CreateWaveDialog", "Create Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.closeWindowButton.setText(QtGui.QApplication.translate("CreateWaveDialog", "Close Window", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CreateWaveDialog", "Wave Data", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.waveDataSelectionList.isSortingEnabled()
        self.waveDataSelectionList.setSortingEnabled(False)
        self.waveDataSelectionList.item(0).setText(QtGui.QApplication.translate("CreateWaveDialog", "Basic Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.item(1).setText(QtGui.QApplication.translate("CreateWaveDialog", "Copy Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.item(2).setText(QtGui.QApplication.translate("CreateWaveDialog", "Custom Function", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(QtGui.QApplication.translate("CreateWaveDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(0, QtGui.QApplication.translate("CreateWaveDialog", "Blank", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(1, QtGui.QApplication.translate("CreateWaveDialog", "Index (starting at 0)", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(2, QtGui.QApplication.translate("CreateWaveDialog", "Index (starting at 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CreateWaveDialog", "Wave Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CreateWaveDialog", "Original Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CreateWaveDialog", "Starting Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CreateWaveDialog", "Ending Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CreateWaveDialog", "Wave Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CreateWaveDialog", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.functionInsertWaveButton.setText(QtGui.QApplication.translate("CreateWaveDialog", "Insert Wave", None, QtGui.QApplication.UnicodeUTF8))

