# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ManageWavesWidget.ui'
#
# Created: Wed Sep  7 23:34:13 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ManageWavesWidget(object):
    def setupUi(self, ManageWavesWidget):
        ManageWavesWidget.setObjectName("ManageWavesWidget")
        ManageWavesWidget.resize(440, 318)
        self.horizontalLayout = QtGui.QHBoxLayout(ManageWavesWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(ManageWavesWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.createWaveTab = QtGui.QWidget()
        self.createWaveTab.setObjectName("createWaveTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.createWaveTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.createWaveTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.createWave_waveName = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createWave_waveName.sizePolicy().hasHeightForWidth())
        self.createWave_waveName.setSizePolicy(sizePolicy)
        self.createWave_waveName.setObjectName("createWave_waveName")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.createWave_waveName)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.createWave_dataType = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createWave_dataType.sizePolicy().hasHeightForWidth())
        self.createWave_dataType.setSizePolicy(sizePolicy)
        self.createWave_dataType.setObjectName("createWave_dataType")
        self.createWave_dataType.addItem("")
        self.createWave_dataType.addItem("")
        self.createWave_dataType.addItem("")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.createWave_dataType)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.createWaveTab)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.waveDataSelectionList = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveDataSelectionList.sizePolicy().hasHeightForWidth())
        self.waveDataSelectionList.setSizePolicy(sizePolicy)
        self.waveDataSelectionList.setMinimumSize(QtCore.QSize(120, 0))
        self.waveDataSelectionList.setObjectName("waveDataSelectionList")
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        QtGui.QListWidgetItem(self.waveDataSelectionList)
        self.horizontalLayout_2.addWidget(self.waveDataSelectionList)
        self.waveDataStack = QtGui.QStackedWidget(self.groupBox_2)
        self.waveDataStack.setFrameShape(QtGui.QFrame.StyledPanel)
        self.waveDataStack.setFrameShadow(QtGui.QFrame.Plain)
        self.waveDataStack.setLineWidth(1)
        self.waveDataStack.setObjectName("waveDataStack")
        self.basicTab = QtGui.QWidget()
        self.basicTab.setObjectName("basicTab")
        self.formLayout = QtGui.QFormLayout(self.basicTab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtGui.QLabel(self.basicTab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.basicWaveType = QtGui.QComboBox(self.basicTab)
        self.basicWaveType.setMinimumSize(QtCore.QSize(150, 0))
        self.basicWaveType.setObjectName("basicWaveType")
        self.basicWaveType.addItem("")
        self.basicWaveType.addItem("")
        self.basicWaveType.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.basicWaveType)
        self.label_9 = QtGui.QLabel(self.basicTab)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.basicWaveLength = QtGui.QSpinBox(self.basicTab)
        self.basicWaveLength.setMaximum(999999)
        self.basicWaveLength.setObjectName("basicWaveLength")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.basicWaveLength)
        self.waveDataStack.addWidget(self.basicTab)
        self.copyTab = QtGui.QWidget()
        self.copyTab.setObjectName("copyTab")
        self.formLayout_3 = QtGui.QFormLayout(self.copyTab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtGui.QLabel(self.copyTab)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.copyWaveOriginalWave = QtGui.QComboBox(self.copyTab)
        self.copyWaveOriginalWave.setObjectName("copyWaveOriginalWave")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.copyWaveOriginalWave)
        self.label_6 = QtGui.QLabel(self.copyTab)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.copyWaveStartingIndex = QtGui.QSpinBox(self.copyTab)
        self.copyWaveStartingIndex.setObjectName("copyWaveStartingIndex")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.copyWaveStartingIndex)
        self.label_8 = QtGui.QLabel(self.copyTab)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.copyWaveEndingIndex = QtGui.QSpinBox(self.copyTab)
        self.copyWaveEndingIndex.setObjectName("copyWaveEndingIndex")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.copyWaveEndingIndex)
        self.waveDataStack.addWidget(self.copyTab)
        self.functionTab = QtGui.QWidget()
        self.functionTab.setObjectName("functionTab")
        self.formLayout_4 = QtGui.QFormLayout(self.functionTab)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.functionTab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.functionWaveLength = QtGui.QSpinBox(self.functionTab)
        self.functionWaveLength.setMaximum(9999999)
        self.functionWaveLength.setObjectName("functionWaveLength")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.functionWaveLength)
        self.label_5 = QtGui.QLabel(self.functionTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.functionEquation = QtGui.QLineEdit(self.functionTab)
        self.functionEquation.setObjectName("functionEquation")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.functionEquation)
        self.functionInsertWaveButton = QtGui.QPushButton(self.functionTab)
        self.functionInsertWaveButton.setObjectName("functionInsertWaveButton")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.functionInsertWaveButton)
        self.functionInsertWave = QtGui.QComboBox(self.functionTab)
        self.functionInsertWave.setObjectName("functionInsertWave")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.functionInsertWave)
        self.waveDataStack.addWidget(self.functionTab)
        self.horizontalLayout_2.addWidget(self.waveDataStack)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.createWaveButton = QtGui.QPushButton(self.createWaveTab)
        self.createWaveButton.setObjectName("createWaveButton")
        self.verticalLayout.addWidget(self.createWaveButton)
        self.tabWidget.addTab(self.createWaveTab, "")
        self.ModifyWaveTab = QtGui.QWidget()
        self.ModifyWaveTab.setObjectName("ModifyWaveTab")
        self.gridLayout = QtGui.QGridLayout(self.ModifyWaveTab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtGui.QGroupBox(self.ModifyWaveTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.modifyWave_waveName = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyWave_waveName.sizePolicy().hasHeightForWidth())
        self.modifyWave_waveName.setSizePolicy(sizePolicy)
        self.modifyWave_waveName.setObjectName("modifyWave_waveName")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.modifyWave_waveName)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.modifyWave_dataType = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyWave_dataType.sizePolicy().hasHeightForWidth())
        self.modifyWave_dataType.setSizePolicy(sizePolicy)
        self.modifyWave_dataType.setObjectName("modifyWave_dataType")
        self.modifyWave_dataType.addItem("")
        self.modifyWave_dataType.addItem("")
        self.modifyWave_dataType.addItem("")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.modifyWave_dataType)
        self.gridLayout.addWidget(self.groupBox_3, 0, 3, 1, 2)
        self.resetWaveButton = QtGui.QPushButton(self.ModifyWaveTab)
        self.resetWaveButton.setObjectName("resetWaveButton")
        self.gridLayout.addWidget(self.resetWaveButton, 1, 3, 1, 1)
        self.modifyWaveButton = QtGui.QPushButton(self.ModifyWaveTab)
        self.modifyWaveButton.setObjectName("modifyWaveButton")
        self.gridLayout.addWidget(self.modifyWaveButton, 1, 4, 1, 1)
        self.removeWaveButton = QtGui.QPushButton(self.ModifyWaveTab)
        self.removeWaveButton.setObjectName("removeWaveButton")
        self.gridLayout.addWidget(self.removeWaveButton, 1, 2, 1, 1)
        self.modifyWave_selectWave = QtGui.QListView(self.ModifyWaveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyWave_selectWave.sizePolicy().hasHeightForWidth())
        self.modifyWave_selectWave.setSizePolicy(sizePolicy)
        self.modifyWave_selectWave.setMinimumSize(QtCore.QSize(100, 0))
        self.modifyWave_selectWave.setMaximumSize(QtCore.QSize(150, 16777215))
        self.modifyWave_selectWave.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.modifyWave_selectWave.setObjectName("modifyWave_selectWave")
        self.gridLayout.addWidget(self.modifyWave_selectWave, 0, 2, 1, 1)
        self.tabWidget.addTab(self.ModifyWaveTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(ManageWavesWidget)
        self.tabWidget.setCurrentIndex(0)
        self.createWave_dataType.setCurrentIndex(1)
        self.waveDataSelectionList.setCurrentRow(-1)
        self.waveDataStack.setCurrentIndex(2)
        QtCore.QObject.connect(self.waveDataSelectionList, QtCore.SIGNAL("currentRowChanged(int)"), self.waveDataStack.setCurrentIndex)

    def retranslateUi(self, ManageWavesWidget):
        ManageWavesWidget.setWindowTitle(QtGui.QApplication.translate("ManageWavesWidget", "Manage Waves", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ManageWavesWidget", "Wave Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Data Type", None, QtGui.QApplication.UnicodeUTF8))
        self.createWave_dataType.setItemText(0, QtGui.QApplication.translate("ManageWavesWidget", "Integer", None, QtGui.QApplication.UnicodeUTF8))
        self.createWave_dataType.setItemText(1, QtGui.QApplication.translate("ManageWavesWidget", "Decimal", None, QtGui.QApplication.UnicodeUTF8))
        self.createWave_dataType.setItemText(2, QtGui.QApplication.translate("ManageWavesWidget", "String", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ManageWavesWidget", "Wave Data", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.waveDataSelectionList.isSortingEnabled()
        self.waveDataSelectionList.setSortingEnabled(False)
        self.waveDataSelectionList.item(0).setText(QtGui.QApplication.translate("ManageWavesWidget", "Basic Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.item(1).setText(QtGui.QApplication.translate("ManageWavesWidget", "Copy Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.item(2).setText(QtGui.QApplication.translate("ManageWavesWidget", "Custom Function", None, QtGui.QApplication.UnicodeUTF8))
        self.waveDataSelectionList.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(QtGui.QApplication.translate("ManageWavesWidget", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(0, QtGui.QApplication.translate("ManageWavesWidget", "Blank", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(1, QtGui.QApplication.translate("ManageWavesWidget", "Index (starting at 0)", None, QtGui.QApplication.UnicodeUTF8))
        self.basicWaveType.setItemText(2, QtGui.QApplication.translate("ManageWavesWidget", "Index (starting at 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ManageWavesWidget", "Original Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ManageWavesWidget", "Starting Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ManageWavesWidget", "Ending Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ManageWavesWidget", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.functionInsertWaveButton.setText(QtGui.QApplication.translate("ManageWavesWidget", "Insert Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.createWaveButton.setText(QtGui.QApplication.translate("ManageWavesWidget", "Create Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.createWaveTab), QtGui.QApplication.translate("ManageWavesWidget", "Create Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ManageWavesWidget", "Wave Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ManageWavesWidget", "Wave Data Type", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyWave_dataType.setItemText(0, QtGui.QApplication.translate("ManageWavesWidget", "Integer", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyWave_dataType.setItemText(1, QtGui.QApplication.translate("ManageWavesWidget", "Decimal", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyWave_dataType.setItemText(2, QtGui.QApplication.translate("ManageWavesWidget", "String", None, QtGui.QApplication.UnicodeUTF8))
        self.resetWaveButton.setText(QtGui.QApplication.translate("ManageWavesWidget", "Reset Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyWaveButton.setText(QtGui.QApplication.translate("ManageWavesWidget", "Modify Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.removeWaveButton.setText(QtGui.QApplication.translate("ManageWavesWidget", "Remove Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ModifyWaveTab), QtGui.QApplication.translate("ManageWavesWidget", "Modify/Remove Wave", None, QtGui.QApplication.UnicodeUTF8))

