# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Fri May 27 16:40:08 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(828, 613)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.workspace = QtGui.QMdiArea(self.centralwidget)
        self.workspace.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.workspace.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.workspace.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.workspace.setDocumentMode(False)
        self.workspace.setObjectName(_fromUtf8("workspace"))
        self.horizontalLayout.addWidget(self.workspace)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuImport = QtGui.QMenu(self.menuFile)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_Table = QtGui.QAction(MainWindow)
        self.actionNew_Table.setObjectName(_fromUtf8("actionNew_Table"))
        self.actionManage_Waves = QtGui.QAction(MainWindow)
        self.actionManage_Waves.setObjectName(_fromUtf8("actionManage_Waves"))
        self.actionManage_Tables = QtGui.QAction(MainWindow)
        self.actionManage_Tables.setObjectName(_fromUtf8("actionManage_Tables"))
        self.actionShow_Waves = QtGui.QAction(MainWindow)
        self.actionShow_Waves.setObjectName(_fromUtf8("actionShow_Waves"))
        self.actionEdit_Figure = QtGui.QAction(MainWindow)
        self.actionEdit_Figure.setObjectName(_fromUtf8("actionEdit_Figure"))
        self.actionShow_Figures = QtGui.QAction(MainWindow)
        self.actionShow_Figures.setObjectName(_fromUtf8("actionShow_Figures"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionSave_Project_As = QtGui.QAction(MainWindow)
        self.actionSave_Project_As.setObjectName(_fromUtf8("actionSave_Project_As"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionModules = QtGui.QAction(MainWindow)
        self.actionModules.setObjectName(_fromUtf8("actionModules"))
        self.actionShow_CWD = QtGui.QAction(MainWindow)
        self.actionShow_CWD.setObjectName(_fromUtf8("actionShow_CWD"))
        self.actionData = QtGui.QAction(MainWindow)
        self.actionData.setObjectName(_fromUtf8("actionData"))
        self.actionPlot = QtGui.QAction(MainWindow)
        self.actionPlot.setObjectName(_fromUtf8("actionPlot"))
        self.actionLoad_Project = QtGui.QAction(MainWindow)
        self.actionLoad_Project.setObjectName(_fromUtf8("actionLoad_Project"))
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionSave_Top_Figure = QtGui.QAction(MainWindow)
        self.actionSave_Top_Figure.setObjectName(_fromUtf8("actionSave_Top_Figure"))
        self.actionSave_Current_Figure = QtGui.QAction(MainWindow)
        self.actionSave_Current_Figure.setObjectName(_fromUtf8("actionSave_Current_Figure"))
        self.menuNew.addAction(self.actionNew_Project)
        self.menuImport.addSeparator()
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_Project_As)
        self.menuFile.addAction(self.actionSave_Current_Figure)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShow_Figures)
        self.menuFile.addAction(self.actionShow_Waves)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PySciPlot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport.setTitle(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuData.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Table.setText(QtGui.QApplication.translate("MainWindow", "New Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Table.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManage_Waves.setText(QtGui.QApplication.translate("MainWindow", "Manage Waves", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManage_Waves.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManage_Tables.setText(QtGui.QApplication.translate("MainWindow", "Manage Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Waves.setText(QtGui.QApplication.translate("MainWindow", "Print Waves", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Figure.setText(QtGui.QApplication.translate("MainWindow", "Edit Figure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Figures.setText(QtGui.QApplication.translate("MainWindow", "Print Figures", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_As.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModules.setText(QtGui.QApplication.translate("MainWindow", "Modules...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_CWD.setText(QtGui.QApplication.translate("MainWindow", "Print CWD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData.setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Project.setText(QtGui.QApplication.translate("MainWindow", "Load Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setText(QtGui.QApplication.translate("MainWindow", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Top_Figure.setText(QtGui.QApplication.translate("MainWindow", "Save Current Figure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Current_Figure.setText(QtGui.QApplication.translate("MainWindow", "Save Current Figure", None, QtGui.QApplication.UnicodeUTF8))

