# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PlotLegend.ui'
#
# Created: Sat May 28 00:16:58 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PlotLegend(object):
    def setupUi(self, PlotLegend):
        PlotLegend.setObjectName(_fromUtf8("PlotLegend"))
        PlotLegend.resize(595, 462)
        self.gridLayout = QtGui.QGridLayout(PlotLegend)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(PlotLegend)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.loc = QtGui.QComboBox(PlotLegend)
        self.loc.setObjectName(_fromUtf8("loc"))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.loc.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.loc, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(PlotLegend)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.title = QtGui.QLineEdit(PlotLegend)
        self.title.setObjectName(_fromUtf8("title"))
        self.gridLayout.addWidget(self.title, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(PlotLegend)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.frameon = QtGui.QCheckBox(PlotLegend)
        self.frameon.setText(_fromUtf8(""))
        self.frameon.setChecked(True)
        self.frameon.setObjectName(_fromUtf8("frameon"))
        self.gridLayout.addWidget(self.frameon, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(PlotLegend)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.fancybox = QtGui.QCheckBox(PlotLegend)
        self.fancybox.setText(_fromUtf8(""))
        self.fancybox.setObjectName(_fromUtf8("fancybox"))
        self.gridLayout.addWidget(self.fancybox, 5, 2, 1, 1)
        self.label_4 = QtGui.QLabel(PlotLegend)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.shadow = QtGui.QCheckBox(PlotLegend)
        self.shadow.setText(_fromUtf8(""))
        self.shadow.setObjectName(_fromUtf8("shadow"))
        self.gridLayout.addWidget(self.shadow, 6, 2, 1, 1)
        self.label_6 = QtGui.QLabel(PlotLegend)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.ncol = QtGui.QSpinBox(PlotLegend)
        self.ncol.setMinimum(1)
        self.ncol.setMaximum(20)
        self.ncol.setObjectName(_fromUtf8("ncol"))
        self.gridLayout.addWidget(self.ncol, 7, 2, 1, 1)
        self.label_7 = QtGui.QLabel(PlotLegend)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 1, 1, 1)
        self.columnspacing = QtGui.QDoubleSpinBox(PlotLegend)
        self.columnspacing.setMaximum(10.0)
        self.columnspacing.setProperty(_fromUtf8("value"), 1.0)
        self.columnspacing.setObjectName(_fromUtf8("columnspacing"))
        self.gridLayout.addWidget(self.columnspacing, 8, 2, 1, 1)
        self.label_8 = QtGui.QLabel(PlotLegend)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 9, 1, 1, 1)
        self.borderaxespad = QtGui.QDoubleSpinBox(PlotLegend)
        self.borderaxespad.setMaximum(10.0)
        self.borderaxespad.setProperty(_fromUtf8("value"), 0.5)
        self.borderaxespad.setObjectName(_fromUtf8("borderaxespad"))
        self.gridLayout.addWidget(self.borderaxespad, 9, 2, 1, 1)
        self.label_9 = QtGui.QLabel(PlotLegend)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 10, 1, 1, 1)
        self.handletextpad = QtGui.QDoubleSpinBox(PlotLegend)
        self.handletextpad.setMaximum(10.0)
        self.handletextpad.setProperty(_fromUtf8("value"), 0.5)
        self.handletextpad.setObjectName(_fromUtf8("handletextpad"))
        self.gridLayout.addWidget(self.handletextpad, 10, 2, 1, 1)
        self.label_10 = QtGui.QLabel(PlotLegend)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 11, 1, 1, 1)
        self.handlelength = QtGui.QDoubleSpinBox(PlotLegend)
        self.handlelength.setMaximum(20.0)
        self.handlelength.setProperty(_fromUtf8("value"), 2.0)
        self.handlelength.setObjectName(_fromUtf8("handlelength"))
        self.gridLayout.addWidget(self.handlelength, 11, 2, 1, 1)
        self.label_11 = QtGui.QLabel(PlotLegend)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 12, 1, 1, 1)
        self.borderpad = QtGui.QDoubleSpinBox(PlotLegend)
        self.borderpad.setMaximum(10.0)
        self.borderpad.setProperty(_fromUtf8("value"), 0.3)
        self.borderpad.setObjectName(_fromUtf8("borderpad"))
        self.gridLayout.addWidget(self.borderpad, 12, 2, 1, 1)
        self.label_12 = QtGui.QLabel(PlotLegend)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 13, 1, 1, 1)
        self.labelspacing = QtGui.QDoubleSpinBox(PlotLegend)
        self.labelspacing.setMaximum(10.0)
        self.labelspacing.setProperty(_fromUtf8("value"), 0.5)
        self.labelspacing.setObjectName(_fromUtf8("labelspacing"))
        self.gridLayout.addWidget(self.labelspacing, 13, 2, 1, 1)
        self.label_13 = QtGui.QLabel(PlotLegend)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 14, 1, 1, 1)
        self.markerscale = QtGui.QDoubleSpinBox(PlotLegend)
        self.markerscale.setMaximum(10.0)
        self.markerscale.setProperty(_fromUtf8("value"), 1.0)
        self.markerscale.setObjectName(_fromUtf8("markerscale"))
        self.gridLayout.addWidget(self.markerscale, 14, 2, 1, 1)
        self.storedSettingsButton = QStoredSettingsButton(PlotLegend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storedSettingsButton.sizePolicy().hasHeightForWidth())
        self.storedSettingsButton.setSizePolicy(sizePolicy)
        self.storedSettingsButton.setMaximumSize(QtCore.QSize(26, 16777215))
        self.storedSettingsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.storedSettingsButton.setArrowType(QtCore.Qt.LeftArrow)
        self.storedSettingsButton.setObjectName(_fromUtf8("storedSettingsButton"))
        self.gridLayout.addWidget(self.storedSettingsButton, 0, 3, 15, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 2, 1, 1)
        self.font = QTextOptionsButton(PlotLegend)
        self.font.setObjectName(_fromUtf8("font"))
        self.gridLayout.addWidget(self.font, 1, 2, 1, 1)
        self.titleFont = QTextOptionsButton(PlotLegend)
        self.titleFont.setObjectName(_fromUtf8("titleFont"))
        self.gridLayout.addWidget(self.titleFont, 3, 2, 1, 1)

        self.retranslateUi(PlotLegend)
        QtCore.QObject.connect(self.frameon, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fancybox.setEnabled)
        QtCore.QObject.connect(self.storedSettingsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.storedSettingsButton.toggleWidget)
        QtCore.QObject.connect(self.font, QtCore.SIGNAL(_fromUtf8("clicked()")), self.font.showTextOptionsWidget)
        QtCore.QObject.connect(self.titleFont, QtCore.SIGNAL(_fromUtf8("clicked()")), self.titleFont.showTextOptionsWidget)

    def retranslateUi(self, PlotLegend):
        PlotLegend.setWindowTitle(QtGui.QApplication.translate("PlotLegend", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PlotLegend", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(0, QtGui.QApplication.translate("PlotLegend", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(1, QtGui.QApplication.translate("PlotLegend", "best", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(2, QtGui.QApplication.translate("PlotLegend", "upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(3, QtGui.QApplication.translate("PlotLegend", "upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(4, QtGui.QApplication.translate("PlotLegend", "lower left", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(5, QtGui.QApplication.translate("PlotLegend", "lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(6, QtGui.QApplication.translate("PlotLegend", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(7, QtGui.QApplication.translate("PlotLegend", "center left", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(8, QtGui.QApplication.translate("PlotLegend", "center right", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(9, QtGui.QApplication.translate("PlotLegend", "lower center", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(10, QtGui.QApplication.translate("PlotLegend", "upper center", None, QtGui.QApplication.UnicodeUTF8))
        self.loc.setItemText(11, QtGui.QApplication.translate("PlotLegend", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PlotLegend", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PlotLegend", "Border", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PlotLegend", "Rounded Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PlotLegend", "Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PlotLegend", "Number of Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PlotLegend", "Spacing between Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PlotLegend", "Border-Axis spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PlotLegend", "Handle-Text padding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PlotLegend", "Handle size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PlotLegend", "Border padding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PlotLegend", "Label line spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PlotLegend", "Marker scale", None, QtGui.QApplication.UnicodeUTF8))
        self.storedSettingsButton.setText(QtGui.QApplication.translate("PlotLegend", "S\n"
"t\n"
"o\n"
"r\n"
"e\n"
"d\n"
"\n"
"S\n"
"e\n"
"t\n"
"t\n"
"i\n"
"n\n"
"g\n"
"s", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setText(QtGui.QApplication.translate("PlotLegend", "Trace Font", None, QtGui.QApplication.UnicodeUTF8))
        self.titleFont.setText(QtGui.QApplication.translate("PlotLegend", "Title Font", None, QtGui.QApplication.UnicodeUTF8))

from gui.QTextOptionsButton import QTextOptionsButton
from gui.QStoredSettingsButton import QStoredSettingsButton
